### ISSUE TITLE
Plugin build error

### ISSUE THREAD

**Issue by phaitonican** [godotengine/webrtc-native#27]
I am getting this error on plugin build:

`[cenk@archlinux webrtc-native]$ scons -j8 platform=android android_arch=arm64v8 target=debug
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `bin/webrtc_debug/lib/libwebrtc_native.android.debug.arm64v8.so' is up to date.
gen_gdnative_lib(["bin/webrtc_debug/webrtc_debug.gdns"], ["misc/gdnlib.tres"])
scons: *** [bin/webrtc_debug/webrtc_debug.gdns] TypeError : a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/SCons/Action.py", line 1209, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "/home/cenk/webrtc-native/SConstruct", line 15, in gen_gdnative_lib
    w.write(source[0].get_contents().replace('{GDNATIVE_PATH}', os.path.splitext(t.name)[0]).replace('{TARGET}', env['target']))
TypeError: a bytes-like object is required, not 'str'
scons: building terminated because of errors.
[cenk@archlinux webrtc-native]$`

Might it has to do that i have to compile with python2? Unfortunately i can't get my system to use scons with python2 xd

**Comment by Faless** [comment]
Yeah, it's a python2 -> python3 issue.
I'll make a PR.
